unpackaged/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>FirstCompetitorAccept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FirstCompetitorAccept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>First Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FirstCompetitor__c</fullName>
        <label>FirstCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondCompetitorAccept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SecondCompetitorAccept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SecondCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Second Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SecondCompetitor__c</fullName>
        <label>SecondCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Stage</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TableTennisAPI.cls
@RestResource(urlMapping='/api/tournaments/*')
global class TableTennisAPI {
	
    @HttpGet
    global static String getTournament() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        if (req.requestURI.contains('/get/')) {
             String tournamentId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        	 List<Tournament__c> ts = [select Id, Name from Tournament__c where Id =: tournamentId];
             return ts.size() > 0 ? JSON.serialize(ts) : 'No such tournament';
        } else {
            return 'wrong request';
        }
    }
    
    @HttpPost
    global static String addTournament(Tournament__c tournament, List<sObject> players) {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        System.debug(tournament);
        Map<Id, Player__c> allPlayers = new Map<Id,Player__c>([select Id from Player__c]);
        System.savepoint sp = Database.setSavepoint();
        if (req.requestURI.contains('/add/')) {
            List<Folder> folders = [select Id, Name from Folder where Name='FolderHttpRequests']; 
            if (folders.size() > 0) {
                Document doc = new Document();
                doc.Name = 'PostHttpTest';
                doc.FolderId = folders.get(0).Id;
                doc.Body = Blob.valueOf(JSON.serialize(tournament)+''+JSON.serialize(players));
                doc.AuthorId = UserInfo.getUserId();
                doc.ContentType = 'text/plain';
                doc.Type = 'txt';
                insert doc;
                System.debug('Success');
                try {
                    if (tournament.StartDate__c==null) tournament.StartDate__c = Datetime.now();
                    upsert tournament;
                    if (tournament.Format__c == '1 x 1') {
                        List<Player__c> playersList = (List<Player__c>) players;
                        List<Player__c> playersListToInsert = new List<Player__c>();
                        for (Player__c pl : playersList) {
                            if (pl.Id != null) {
                                if (!allPlayers.containsKey(pl.Id)) {
                                	//playersListToInsert.add(pl);
                                }
                            } else {
                                playersListToInsert.add(pl);
                            }
                        }
                        insert playersListToInsert;
                        List<PlayerTournament__c> playerTournaments = new List<PlayerTournament__c>();
                        for (Player__c player : playersList) {
                            playerTournaments.add(new PlayerTournament__c(Player__c = player.Id, Tournament__c = tournament.Id));
                        }
                        insert playerTournaments;
                    }
                } catch (Exception ex) {
                    Database.rollback(sp);
                    return ex.getMessage();
                }
            } else {
                System.debug('wrong address');
            }
        }
        TournamentStarter ts = new TournamentStarter();
        ts.start(tournament);
        String gamesJSON = '';
        List<Game__c> games = [select Id, FirstCompetitor__c, SecondCompetitor__c, FirstCompetitorScore__c, SecondCompetitorScore__c,
                               Stage__c, FirstCompetitorAccept__c, SecondCompetitorAccept__c, Type__c
                               from Game__c where Tournament__c =: tournament.Id];
        gamesJSON = JSON.serialize(games);
        Database.rollback(sp);
        return JSON.serialize(games);
    }
}