unpackaged/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rating</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Active</fullName>
                    <default>true</default>
                    <label>Not Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/PlayerStatisticsSorterTest.cls
/**
 * Created by rostyk_haidukevych on 9/22/17.
 */
@IsTest
public class PlayerStatisticsSorterTest {

	static testmethod void singleEliminationTournamentStart(){
		List<Player__c> players = new List<Player__c>();
		Datetime dt = Datetime.now();
		Tournament__c setTournament = new Tournament__c(Name = 'setTournament', Format__c = '1 x 1', Status__c = 'Upcoming', Type__c = 'Single Elimination', StartDate__c = dt);
		insert setTournament;

		Player__c player = new Player__c(Name = 'Name1', Email__c = 'name1@gmail.com', Status__c = 'Active', Password__c = '12345678', Rating__c = 0);
		players.add(player);

		player = new Player__c(Name = 'Name2', Email__c = 'name2@gmail.com', Status__c = 'Active', Password__c = '12345678', Rating__c = 1);
		players.add(player);

		player = new Player__c(Name = 'Name3', Email__c = 'name3@gmail.com', Status__c = 'Active', Password__c = '12345678', Rating__c = 5);
		players.add(player);

		player = new Player__c(Name = 'Name4', Email__c = 'name4@gmail.com', Status__c = 'Active', Password__c = '12345678', Rating__c = 3);
		players.add(player);

		player = new Player__c(Name = 'Name5', Email__c = 'name5@gmail.com', Status__c = 'Active', Password__c = '12345678', Rating__c = 2);
		players.add(player);


		player = new Player__c(Name = 'Name6', Email__c = 'name6@gmail.com', Status__c = 'Active', Password__c = '12345678', Rating__c = 4);
		players.add(player);


		insert players;

		System.assertEquals(players.size(), 6);


		List<PlayerTournament__c> playerTournaments = new List<PlayerTournament__c>();
		for (Player__c currentPlayer: players){
			playerTournaments.add(new PlayerTournament__c(Player__c = currentPlayer.Id, Tournament__c = setTournament.Id));
		}

		insert playerTournaments;

		System.assertEquals(playerTournaments.size(), 6);

		TournamentStarter ts = new TournamentStarter();
		ts.start(setTournament);


		System.assertEquals([select Id from Game__c].size(), 6);

	}

}