unpackaged/objects/Game__c.object
<CustomObject>
    <fields>
        <fullName>FirstCompetitorAccept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>FirstCompetitorAccept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FirstCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>First Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FirstCompetitor__c</fullName>
        <label>FirstCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecondCompetitorAccept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SecondCompetitorAccept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SecondCompetitorScore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Second Competitor Score</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SecondCompetitor__c</fullName>
        <label>SecondCompetitor</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Games</relationshipLabel>
        <relationshipName>Games</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>Game</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Game Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Player__c.object
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/PlayerTeam__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTeam</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTeams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>IsComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsComplete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/AURA_GameController.cls
/**
 * Created by rostyk_haidukevych on 11/7/17.
 */
public class AURA_GameController {

	public Boolean currentPlayerInsertedScore {get;set;}
	public Boolean competitorInsertedScore {get;set;}

	@AuraEnabled
	public static String insertScore(String tournamentId, String currentPlayer, Game__c game) {
		Tournament__c tournament = [select Id, Name, Type__c, Format__c from Tournament__c where Id=:tournamentId];
		CallBackMessage callBackMessage = new CallBackMessage();
		Integer firstCompScore = (Integer)game.FirstCompetitorScore__c;
		Integer secondCompScore = (Integer)game.SecondCompetitorScore__c;
		if ((firstCompScore>=0 && secondCompScore >=0) && (firstCompScore != secondCompScore)) {
			game.FirstCompetitorScore__c = firstCompScore;
			game.SecondCompetitorScore__c = secondCompScore;
		} else {
			callBackMessage.type = 'Error';
			callBackMessage.message = 'Values must be different and at least >=0';
			return JSON.serialize(callBackMessage);
		}
		PlayerCookiePositionInGame positionInGame = playerPositionInCurrentGame(tournament, currentPlayer, game);
		if (positionInGame==PlayerCookiePositionInGame.FIRST_COMPETITOR) {
			game.FirstCompetitorAccept__c = true;
			game.SecondCompetitorAccept__c = false;
			update game;
			GameController.sendNotifications(game.FirstCompetitor__c, game.Id);
		} else if (positionInGame == PlayerCookiePositionInGame.SECOND_COMPETITOR) {
			game.FirstCompetitorAccept__c = false;
			game.SecondCompetitorAccept__c = true;
			update game;
			GameController.sendNotifications(game.SecondCompetitor__c, game.Id);
		} else {
			callBackMessage.type = 'ERROR';
			callBackMessage.message = 'Player from cookie is not present in current game';
		}
		callBackMessage.type = 'SUCCESS';
		callBackMessage.message = 'Game was successfully updated';
		return JSON.serialize(callBackMessage);
	}


	@AuraEnabled
	public static Boolean defineIfPlayerCanSubmitCurrentGame(Id tournamentId,  String currentPlayer, String gameId){
		Tournament__c tournament = [select Id, Name, Type__c, Format__c from Tournament__c where Id=:tournamentId];
		Game__c game = findGame(gameId);
		PlayerCookiePositionInGame positionInGame = playerPositionInCurrentGame(tournament, currentPlayer, game);
		if (positionInGame==PlayerCookiePositionInGame.FIRST_COMPETITOR) {
			if (game.SecondCompetitorAccept__c) {
				return true;
			}
		} else if (positionInGame==PlayerCookiePositionInGame.SECOND_COMPETITOR){
			if (game.FirstCompetitorAccept__c) {
				return true;
			}
		} else {
			return false;
		}
		return false;
	}


	@AuraEnabled
	public static Game__c findGame(String gameId) {
		return [select Id, FirstCompetitor__c, SecondCompetitor__c, FirstCompetitorAccept__c, SecondCompetitorAccept__c, FirstCompetitorScore__c, SecondCompetitorScore__c from Game__c where Id=:gameId];
	}


	@AuraEnabled
	public static String submitScore(Tournament__c tournament, String currentPlayer, Game__c game) {
		CallBackMessage callBackMessage = new CallBackMessage();
		PlayerCookiePositionInGame positionInGame = playerPositionInCurrentGame(tournament, currentPlayer, game);
		if (positionInGame==PlayerCookiePositionInGame.FIRST_COMPETITOR) {
			if (game.SecondCompetitorAccept__c) {
				game.FirstCompetitorAccept__c = true;
				update game;
			} else {
				callBackMessage.type = 'ERROR';
				callBackMessage.message = 'You can not sumbit score of the game, that was inserted by you';
				return JSON.serialize(callBackMessage);
			}
		} else if (positionInGame==PlayerCookiePositionInGame.SECOND_COMPETITOR){
			if (game.FirstCompetitorAccept__c) {
				game.SecondCompetitorAccept__c = true;
				update game;
			} else {
				callBackMessage.type = 'ERROR';
				callBackMessage.message = 'You can not sumbit score of the game, that was inserted by you';
				return JSON.serialize(callBackMessage);
			}
		} else {
			callBackMessage.type = 'ERROR';
			callBackMessage.message = 'Player from cookie is not present in current game';
			return JSON.serialize(callBackMessage);
		}


		callBackMessage.type = 'SUCCESS';
		callBackMessage.message = 'Game was successfully updated';
		return JSON.serialize(callBackMessage);
	}


	private static PlayerCookiePositionInGame playerPositionInCurrentGame(Tournament__c tournament, String currentPlayer, Game__c game) {
		String firstCompetitorStr = ''+game.FirstCompetitor__c;
		String secondCompetitorStr = ''+game.SecondCompetitor__c;
		if (tournament.Format__c == '1 x 1') {
			if (firstCompetitorStr.contains(currentPlayer)) {
				return PlayerCookiePositionInGame.FIRST_COMPETITOR;
			} else if (secondCompetitorStr.contains(currentPlayer)){
				return PlayerCookiePositionInGame.SECOND_COMPETITOR;
			}
		} else {
			String playerLikeCurrent = '%'+currentPlayer+'%';
			PlayerTeam__c idOfTeamWhereCurrentPlayerIsPresent = [select Team__c from PlayerTeam__c where Player__c =: playerLikeCurrent
					and Team__c =: game.FirstCompetitor__c and Team__r.IsComplete__c = true];

			if (firstCompetitorStr.contains(idOfTeamWhereCurrentPlayerIsPresent.Team__c)) {
				return PlayerCookiePositionInGame.FIRST_COMPETITOR;
			} else if (secondCompetitorStr.contains(idOfTeamWhereCurrentPlayerIsPresent.Team__c)){
				return PlayerCookiePositionInGame.SECOND_COMPETITOR;
			}
		}

		return PlayerCookiePositionInGame.NOT_PRESENT;
	}


	public class CallBackMessage {
		String type;
		String message;
	}

}