unpackaged/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Active</fullName>
                    <default>true</default>
                    <label>Not Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/PlayerTournament__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>PlayerTournaments</relationshipLabel>
        <relationshipName>PlayerTournaments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTournament</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTournament Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTournaments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>IsComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsComplete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TournamentStarter.cls
global class TournamentStarter implements Schedulable {

    global void execute(SchedulableContext ctx) {
        DateTime dt = DateTime.now();
        List<Tournament__c> tournamentsToStart = [SELECT Id, Name, Type__c, Format__c, Status__c, StartDate__c 
            FROM Tournament__c 
            WHERE Status__c = 'Upcoming' AND StartDate__c <= :dt];
        // Let's make a limit to start only 3 tournaments for one time to be sure that we will not exceed salesforce limits
        for(integer i = 0; i < (tournamentsToStart.size() > 3 ? 3 : tournamentsToStart.size()); i++) {
            start(tournamentsToStart[i]);
        }
    }
    
    public void start(Tournament__c tournament) {
        try {
            tournament.Status__c = 'Current';
            update(tournament);
            generateGames(tournament);
        } catch (Exception e) {
            System.debug(e);
        }
    }
    
    private void generateGames(Tournament__c tournament) {
        System.debug('Tournament:'+tournament);
        List<String> ids = getCompetitorsIds(tournament);

        
        ids = PlayerStatisticsSorter.sortPlayersByStatistics(ids,tournament);
        System.debug('ids'+ids);
        Integer pairs = ids.size() / 2;
        List<String> idsUpdated = new List<String>();
        for (Integer i = 0; i < pairs; i++){
            idsUpdated.add(ids.get(i));
            idsUpdated.add(ids.get(ids.size()-i-1));
        }

        if (Math.mod(ids.size() , 2) == 1) {
            idsUpdated.add(ids.get(pairs));
        }
        
        List<String> idsAll = new List<String>();
        idsAll.addAll(ids);
        idsAll.add('\r\n--------------\r\n');
        idsAll.addAll(idsUpdated);

        try {
            Document doc = [select Body from Document where Name='NewTournamentCurrent' limit 1];
            doc.Body = Blob.valueOf(JSON.serialize(ids) + '\r\n---------\r\n' + JSON.serialize(idsUpdated));
            update doc;
        } catch (Exception ex){

        }
        
        if (tournament.Type__c == 'Single Elimination') {
            SingleEliminationTournament.StartSingleEliminationTournament(idsUpdated, tournament);
        } else if (tournament.Type__c == 'Double Elimination') {
            DoubleEliminationTournament.generateRounds(idsUpdated, tournament.Id);
        } else {
            RoundRobin.RoundRobinTournament(tournament, ids);
        }
    }
    
    private List<String> getCompetitorsIds(Tournament__c tournament) {
        List<String> result;
        if (tournament.Format__c == '1 x 1') {
            result = getPlayersIds(tournament.Id);
        } else {
            result = getTeamsIds(tournament.Id);
        }
        return result;
    }
    
    private List<String> getPlayersIds(String tournamentId) {
        List<String> result = new List<String>();
        List<PlayerTournament__c> playerTournaments = [SELECT Player__c 
            FROM PlayerTournament__c 
            WHERE Tournament__c = :tournamentId];
        for (PlayerTournament__c pT : playerTournaments) {
            result.add(pT.Player__c);
        }
        return result;
    }
    
    private List<String> getTeamsIds(String tournamentId) {
        List<String> result = new List<String>();
        List<Team__c> teams = [SELECT Id 
            FROM Team__c 
            WHERE Tournament__c = :tournamentId AND IsComplete__c = true];
        for (Team__c t : teams) {
            result.add(t.Id);
        }
        return result;
    }
}