unpackaged/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>Url of player&apos;s Image</description>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/PlayerCredentials.cls
@RestResource(urlMapping='/players/credentials/*')
global class PlayerCredentials {

    @HttpGet
    global static String doGet(){
        RestRequest req = RestContext.request;
        
        String email = req.params.get('email');
        String password = req.params.get('password');
        
        String userId = req.headers.get('From');
       
        
        List<User> users = [select Id from User where Id =: userId];
        
        if (users.size() > 0) {
            List<Player__c> players = [select Id, Name, IsManager__c, Password__c, Image__c from Player__c where Email__c =:email];
            if (players.size() > 0) {
                if (players.get(0).Password__c.equals(password)) {
                    return JSON.serialize(players.get(0)).replaceAll('"','\'');
                } else {
                    return '{\'message\':\'wrong password\'}';
                }
            }
        }
        return '{\'message\':\'wrong email\'}';
    }

}