unpackaged/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>16</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/PlayerCookie.cls
public with sharing abstract class PlayerCookie {
    public Player__c currentPlayer {get;set;}
    public Boolean isLoggedIn {get;set;}
    public Boolean isManager{get;set;}
    public static String playerCookieId = '';
    
    
    public PlayerCookie(){
       try {
           isLoggedIn = ApexPages.currentPage().getCookies().get('PlayerFromCookie') != null;
           if (isLoggedIn) {
               Id playerId = ApexPages.currentPage().getCookies().get('PlayerFromCookie').getValue();
               currentPlayer = [select Id,Name,Email__c,Password__c,IsManager__c from Player__c where Id = :playerId];
               isManager = currentPlayer.isManager__c;
               playerCookieId = currentPlayer.Id;
           } else isManager = false;
       } catch (Exception ex) {
           isManager = false;
       }
    }
    
    public Player__c getCurrentPlayer(){
        if (ApexPages.currentPage().getCookies().get('PlayerFromCookie')!=null) {
            Id playerId = ApexPages.currentPage().getCookies().get('PlayerFromCookie').getValue();
            currentPlayer = [select Id,Name,Email__c,Password__c,IsManager__c from Player__c where Id = :playerId];
            playerCookieId = currentPlayer.Id;
            return currentPlayer;
        } else return new Player__c(); 
    }
}