unpackaged/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>Url of player&apos;s Image</description>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Active</fullName>
                    <default>true</default>
                    <label>Not Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/PlayerTeam__c.object
<CustomObject>
    <fields>
        <fullName>Player__c</fullName>
        <label>Player</label>
        <referenceTo>Player__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <referenceTo>Team__c</referenceTo>
        <relationshipLabel>PlayerTeams</relationshipLabel>
        <relationshipName>PlayerTeams</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PlayerTeam</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>PlayerTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PlayerTeams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/AURA_PlayerController.cls
public class AURA_PlayerController { 
    @AuraEnabled
    public static List<Player__c> getPlayersByInput(Player__c player){
        String searchName = player != null ? '%'+player.Name+'%' : '%%';
        String status = player != null ? '%'+player.Status__c+'%' : '%%';
        List<Player__c> players = [select Name,Email__c,Status__c,Image__c from Player__c where (Name like: searchName or Email__c like: searchName)
                                  and Status__c like : status];
        return players;
    }


    @AuraEnabled
    public static String getPlayerStatistics(Id tournamentId, Id playerId) {
        Tournament__c tournament = [select Id, Format__c, Status__c from Tournament__c where Id=:tournamentId];
        Player__c player = null;
        Team__c team = null;
        if (tournament.Format__c == '1 x 1') {
            player = [select Id, Name, Image__c from Player__c where Id=:playerId];
        }
        PlayerController pc = new PlayerController();
        StatisticsOfPlayer statisticsOfPlayer = new StatisticsOfPlayer();
        try {
            if (tournament.Format__c == '1 x 1') {
                if (tournament.Status__c != 'Upcoming') {
                    pc.currentOrCompletedTournamentId = tournamentId;
                    pc.player = player;
                    pc.getCurrentOrCompletedTournament();
                    System.debug('cwg:'+pc.countWonGames+',clg:'+pc.countLostGames);
                    statisticsOfPlayer.countWonGames = pc.countWonGames;
                    statisticsOfPlayer.countLostGames = pc.countLostGames;
                    statisticsOfPlayer.urlImage = '' + player.Image__c;
                    statisticsOfPlayer.playerName = player.Name;
                    statisticsOfPlayer.tournamentFormat = '1 x 1';
                }
            } else {
                team = [select Id, (select Player__r.Name from PlayerTeams__r) from Team__c where Id=:playerId];
                statisticsOfPlayer.player1OfTeamName = team.PlayerTeams__r.get(0).Player__r.Name;
                statisticsOfPlayer.player2OfTeamName = team.PlayerTeams__r.get(1).Player__r.Name;
                statisticsOfPlayer.tournamentFormat = '2 x 2';
            }
            return JSON.serialize(statisticsOfPlayer);
        } catch (Exception ex){
            return '';
        }
    }

    class StatisticsOfPlayer {
        Double countWonGames;
        Double countLostGames;
        String urlImage;
        String playerName;
        String player1OfTeamName;
        String player2OfTeamName;
        String tournamentFormat;
    }

}