unpackaged/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>Url of player&apos;s Image</description>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>IsManager__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsManager</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Active</fullName>
                    <default>true</default>
                    <label>Not Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/TournamentsApi.cls
@RestResource(urlMapping='/api/get/tournaments/*')
global class TournamentsApi {

    @HttpGet
    global static String doGet(){
        RestRequest req = RestContext.request;
        String tournamentsArr='[';
        //if (req.requestURI.substring(req.requestURI.lastIndexOf('/'), 
                //req.requestURI.length()).contains('player')) {
                String playerId = req.params.get('playerId');
                System.debug('PlayerId: '+playerId);
                if (!String.isEmpty(playerId)) {
                    List<Player__c> players = [select Id,Name,Email__c,IsManager__c,Image__c from Player__c where Id =: playerId];
                    System.debug('Players : '+players);
                    if (players.size() > 0) {
                        Player__c player = players.get(0);
                        PlayerController playerCtrl = new PlayerController();
                        playerCtrl.player = player;
                        playerCtrl.getPlayerTournaments();
                        System.debug('Tournaments (current or completed) size : '+ playerCtrl.tournamentsOfPlayer);
                        for (Tournament__c tournament : playerCtrl.tournamentsOfPlayer) {
                            if (tournament.Status__c != 'Upcoming') {
                                tournamentsArr+=makeTournament(tournament);
                           }
                        }
                        tournamentsArr = tournamentsArr.substring(0,tournamentsArr.length()-1);
                    }
                }  
        //}
        tournamentsArr+=']';
        return tournamentsArr;
    }
    
    
    private static String makeTournament(Tournament__c tournament){
        String tournamentJSON = '{\'Id\' : \''+tournament.Id+'\''
        +makeOneField('Name', tournament.Name)
        +makeOneField('Status__c', tournament.Status__c)
        +makeOneField('Format__c', tournament.Format__c)
        +makeOneField('Type__c', tournament.Type__c)
        +'},';
        return tournamentJSON;
    }
    
    private static String makeOneField(String fieldName, String value) {
        return ',\''+fieldName+'\' : \''+value+'\'';
    }

}