unpackaged/objects/Player__c.object
<CustomObject>
    <fields>
        <fullName>Image__c</fullName>
        <description>Url of player&apos;s Image</description>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rating</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Active</fullName>
                    <default>true</default>
                    <label>Not Active</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Player</label>
    <nameField>
        <label>Player Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Tournament__c</fullName>
        <label>Tournament</label>
        <referenceTo>Tournament__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/AURA_TeamController.cls
/**
 * Created by rostyk_haidukevych on 11/7/17.
 */
public class AURA_TeamController {

	@AuraEnabled
	public static String getAllInvitations(String playerId){
		Player__c player = [select Id, Name, Status__c, Rating__c, Image__c from Player__c where Id =: playerId];
		PlayerTeamController ptc = new PlayerTeamController();
		ptc.currentPlayer2 = player;
		return JSON.serialize(ptc.teamInvitations);
	}


	@AuraEnabled
	public static String acceptTeamInvitation(String teamId, String playerFromCookieId, String playerId) {
		Team__c team = [select Id, Tournament__c from Team__c where Id=:teamId];
		PlayerTeamController ptc = new PlayerTeamController();
		ptc.invitationTeamId = team.Id;
		ptc.invitationPlayerId = [select Id from Player__c where Id =: playerId].Id;
		ptc.currentPlayer2 = [select Id from Player__c where Id=:playerFromCookieId];
		ptc.acceptInvitation();
		Tournament__c tournament = [SELECT Id, Name, Type__c, Format__c, Status__c, StartDate__c
				FROM Tournament__c
				WHERE Id = :team.Tournament__c];
		TournamentController.TournamentWrapper tw = new TournamentController.TournamentWrapper();
		tw.tournament = tournament;
		tw.isApplied = true;
		tw.isShowed = true;
		return JSON.serialize(tw);
	}


	@AuraEnabled
	public static void declineTeamInvitation(String teamId) {
		Team__c team = [select Id, Tournament__c from Team__c where Id=:teamId];
		delete team;
	}

}