unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/AURA_SingleElimination.cls
/**
 * Created by rostyk_haidukevych on 10/10/17.
 */
public class AURA_SingleElimination {

	@AuraEnabled
	public static String getAllGamesJSONS(Id tournamentId, String playerId, String pageName){
		Tournament__c tournament = [select Id, Name, Format__c, Status__c, Type__c from Tournament__c where Id =: tournamentId limit 1];
		System.debug('tournament: '+tournament);
		SingleEliminationTournament se = new SingleEliminationTournament();
		se.oneTournament = tournament;
		se.lightningSync = true;
		se.lightningPageName = pageName;
		try {
			se.playerIdLightning = playerId;
		} catch (StringException ex){
			System.debug('String exception');
			se.playerIdLightning = null;
		}
		System.debug(JSON.serialize(se.representSingleEliminationGrid));
		return JSON.serialize(se.representSingleEliminationGrid);
	}

}