unpackaged/objects/Tournament__c.object
<CustomObject>
    <fields>
        <fullName>Format__c</fullName>
        <label>Format</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1 x 1</fullName>
                </value>
                <value>
                    <fullName>2 x 2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Round Robin</fullName>
                </value>
                <value>
                    <fullName>Single Elimination</fullName>
                </value>
                <value>
                    <fullName>Double Elimination</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tournament</label>
    <nameField>
        <label>Tournament Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tournaments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/AURA_DoubleElimination.cls
/**
 * Created by rostyk_haidukevych on 10/6/17.
 */
public class AURA_DoubleElimination {


	@AuraEnabled
	public static String getAllGamesJSONS(Id tournamentId, String playerId, String pageName){
		Tournament__c tournament = [select Id, Name, Format__c, Status__c, Type__c from Tournament__c where Id =: tournamentId limit 1];
		DoubleEliminationTournament de = new DoubleEliminationTournament();
		de.oneTournament = tournament;
		de.lightningSync = true;
		try {
			de.playerIdLightning = playerId;
		} catch (StringException ex){
			System.debug('String exception');
			de.playerIdLightning = null;
		}
		de.lightningPageName = pageName;
        System.debug('de:'+de.playerIdLightning);
        System.debug('de:'+de.oneTournament);
		System.debug(JSON.serialize(de.representDoubleEliminationGridJSON));
		return JSON.serialize(de.representDoubleEliminationGridJSON);
	}

}